CREATE TABLE CATEGORIES(
    CATEGORY VARCHAR
);

CREATE TABLE WIKI(
    create_timestamp TIMESTAMP,
    TIME_STAMP TIMESTAMP,
    lang LANGUAGE,
    wiki VARCHAR,
    title VARCHAR PRIMARY KEY,
    auxiliary_text VARCHAR,
    CONSTRAINT CATEGORY FOREIGN KEY REFERENCES CATEGORIES
);